### ISSUE TITLE
Missing .ipynb notebooks when cloning repo

### ISSUE THREAD

**Issue by kakoatao** [ramanakumars/SolarJets#30]
3 of the Jupyter Notebooks aren't being moved to the cloned directory. I am not sure why this is, I don't see them excluded in .gitignore.
`JetOrNot/jetornot.ipynb`
`JetOrNot/jet_time_distribution.ipynb`
`BoxTheJets/Plotting_agreement_T3.ipynb`

**Comment by ramanakumars** [comment]
Let me know if those commands don't work.

**Comment by kakoatao** [comment]
They are all there now after the hard reset command. Thank you
