### ISSUE TITLE
JetOrNot.ipynb files in wrong directory

### ISSUE THREAD

**Issue by kakoatao** [ramanakumars/SolarJets#34]
In cells 11 and 18, we look for the file `question_extractor_trimmed.csv`. This file is located in `extracts/`, so these should be changed to read `extracts/question_extractor_trimmed.csv`.

**Comment by ramanakumars** [comment]
I think jetornot needs to be completely modified. We know the reason for the high vote count subjects, so I think it should instead be more like plotting_agreement_T0 but per subject instead of per SOL event.
